user_name = input("What is your name? \n")
user_age = input("How old are you? \n")
user_address = input("Where are you live? \n")
print("Hello,", user_name +"!")
print("Your age is", user_age + ".")
print("You live in", user_address + ".")